Resources:

  # RdsSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     VpcId:
  #       Ref: 'VPC'
  #     GroupDescription: Allow MySQL (TCP3306)
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: 3306
  #         ToPort: 3306
  #         CidrIp:
  #           Ref: AppSubnet1

  #     Tags:
  #       - Key: CloudFormationArn
  #         Value:
  #           Ref 'AWS::StackId'


  MonitoringRdsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - monitoring.rds.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
      Path: /

  RDSDBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: CloudFormation Aurora Cluster Parameter Group
      Family: aurora5.6
      Parameters:
        server_audit_logging: 0
        server_audit_events: 'CONNECT,QUERY,QUERY_DCL,QUERY_DDL,QUERY_DML,TABLE'
      Tags:
        - Key: CloudFormationArn
          Value:
            Ref: 'AWS::StackId'

  RDSDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: CloudFormation Aurora Parameter Group
      Family: aurora5.6
      Parameters:
        aurora_lab_mode: 0
        general_log: 1
        slow_query_log: 1
        long_query_time: 10
      Tags:
        - Key: CloudFormationArn
          Value:
            Ref: 'AWS::StackId'

  LogGroupRdsError:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ''
          - - '/aws/rds/cluster/'
            - Ref: 'AWS::StackName'
            - '/error'
      RetentionInDays: 14

  LogGroupRdsGeneral:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ''
          - - '/aws/rds/cluster/'
            - Ref: 'AWS::StackName'
            - '/general'
      RetentionInDays: 14

  RDSCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername:
        Ref: DBMasterUsername
      MasterUserPassword:
        Ref: DBMasterPassword
      Engine: aurora
      DBSubnetGroupName:
        Ref: RDSSubnetGroup
      DBClusterParameterGroupName:
        Ref: RDSDBClusterParameterGroup
  RDSDBInstance1:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName:
        Ref: RDSSubnetGroup
      DBParameterGroupName:
        Ref: RDSDBParameterGroup
      Engine: aurora
      DBClusterIdentifier:
        Ref: RDSCluster
      PubliclyAccessible: 'false'
      AvailabilityZone:
        Fn::GetAtt:
        - DBSubnet1
        - AvailabilityZone
      DBInstanceClass: db.t2.small
      AutoMinorVersionUpgrade: 'true'
      PreferredMaintenanceWindow: Thu:19:35-Thu:20:35
      MonitoringInterval: 60
      MonitoringRoleArn:
        Fn::GetAtt:
        - MonitoringRdsRole
        - Arn

  RDSDBInstance2:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName:
        Ref: RDSSubnetGroup
      DBParameterGroupName:
        Ref: RDSDBParameterGroup
      Engine: aurora
      DBClusterIdentifier:
        Ref: RDSCluster
      PubliclyAccessible: 'false'
      AvailabilityZone:
        Fn::GetAtt:
        - DBSubnet2
        - AvailabilityZone
      DBInstanceClass: db.t2.small
      AutoMinorVersionUpgrade: 'true'
      PreferredMaintenanceWindow: Thu:20:35-Thu:21:35
      MonitoringInterval: 60
      MonitoringRoleArn:
        Fn::GetAtt:
        - MonitoringRdsRole
        - Arn

  # RDSDBInstance3:
  #   Type: AWS::RDS::DBInstance
  #   Properties:
  #     DBSubnetGroupName:
  #       Ref: RDSSubnetGroup
  #     DBParameterGroupName:
  #       Ref: RDSDBParameterGroup
  #     Engine: aurora
  #     DBClusterIdentifier:
  #       Ref: RDSCluster
  #     PubliclyAccessible: 'false'
  #     AvailabilityZone:
  #       Fn::GetAtt:
  #       - DBSubnet3
  #       - AvailabilityZone
  #     DBInstanceClass: db.t2.small
  #     AutoMinorVersionUpgrade: 'true'
  #     PreferredMaintenanceWindow: Thu:20:35-Thu:21:35
  #     MonitoringInterval: 60
  #     MonitoringRoleArn:
  #       Fn::GetAtt:
  #       - MonitoringRdsRole
  #       - Arn

Outputs:
  RDSClusterEndpoint:
    Description: Database Cluster URL Endpoint.
    Value:
      Fn::GetAtt:
        - 'RDSCluster'
        - 'Endpoint.Address'

  RDSClusterReadEndpoint:
    Description: Database Cluster Read URL Endpoint.
    Value:
      Fn::GetAtt:
        - 'RDSCluster'
        - 'ReadEndpoint.Address'
